# Generated by Django 3.1.1 on 2020-09-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200914_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sgxuser',
            options={'verbose_name': 'SGX 사용자', 'verbose_name_plural': 'SGX 사용자'},
        ),
    ]
