# Generated by Django 3.1.1 on 2020-09-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200914_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgxuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
